services:
  app:
    container_name: go_app
    build: .
    env_file: .env.prod
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - migrate
      - mongo
    networks:
      - backend_net


  postgres:
    image: postgres:16
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_net

  mongo:
    image: mongo:7
    container_name: app_mongo
    restart: always
    volumes:
      - mongodata:/data/db
    networks:
      - backend_net

  migrate:
    image: migrate/migrate
    container_name: app_migrate
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:postgres@db:5432/appdb?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  pgdata:
  mongodata:
